In [17]:
import numpy as np

populacao = np.arange(1, 501)  # 500 alunos numerados
amostra = np.random.choice(populacao, size=5, replace=False)

In [ ]:
populacao

In [19]:
amostra

array([198, 417, 258, 214, 142])

Amostragem sistemática: Seleciona-se um elemento inicial aleatório, depois escolhe-se cada k-ésimo elemento.

In [29]:
N = 500
n = 10
k = N // n

inicio = np.random.randint(1, k+1)
amostra = list(range(inicio, N+1, k))

In [30]:
k

50

In [31]:
inicio

11

In [32]:
amostra

[11, 61, 111, 161, 211, 261, 311, 361, 411, 461]

In [42]:
# amostragem estratificada
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'id': range(1, 501),
    'sexo': ['M']*300 + ['F']*200
})

amostra = df.groupby('sexo').sample(frac=0.2, random_state=42)  # 10% de cada grupo

In [41]:
df['sexo'].value_counts()

sexo
M    300
F    200
Name: count, dtype: int64

In [34]:
amostra

      id sexo
483  484    F
453  454    F
470  471    F
445  446    F
444  445    F
..   ...  ...
82    83    M
0      1    M
11    12    M
249  250    M
22    23    M

[100 rows x 2 columns]

In [43]:
df['sexo'].value_counts()

sexo
M    300
F    200
Name: count, dtype: int64

In [44]:
amostra['sexo'].value_counts()

sexo
M    60
F    40
Name: count, dtype: int64